# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude:  |
    (?x)^(
        (.vscode|.github/|tests|docs)/.* |
        jade/(install_files|default_settings|resources)/.* |
        tests/TestFiles/.* |
        LICENSE.*|
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
